### ISSUE TITLE
[feedback] when listing tracks returned by query, show banger status next to track info

### ISSUE THREAD

**Issue by inoland** [derekdapp/isitabangr#1]
For user ease of use I think it would be helpful if when listing tracks returned it just showed the banger status to the right of it. It would save on the loading times/page requests, and would save the user from having to click on the track and then pressing back to go back to the search.

**Comment by derekdapp** [comment]
Hey Isaac,
I considered this, but I decided not to because it would actually greatly
increase server load and cause quite a few problems. The searching is done
through spotify, so I can do that an unlimited amount of times. The only
time I actually connect to echonest is when the song is being searched for
for the first time. I did it this way because there is a limit to how many
echonest queries I can do. If its not the first time, then I already have
the information on my side of the server. This is the reason why I've been
able to avoid the Reddit hug of death today. Hope that makes sense!
-Derek
